doall_Avg_theta_seq_both
doall_Avg_theta_seq_both_exfg
doall_Avg_theta_seq_both_dsfg


doall_Avg_theta_seq_both_section
doall_Avg_theta_seq_both_exfg_section
doall_Avg_theta_seq_both_dsfg_section

doall_decoding_CT_v5
doall_decoding_CT_exclude_cellfg
doall_decoding_CT_downsamp_cellfg


doall_decoding_CT_exclude_cellfgv2
doall_decoding_CT_downsamp_cellfgv2

doall_get_gammaZ_wn_v4
doall_VFR_gammaZ_v8